"""add event_type and rename description to raw_description

Revision ID: 19e423d8523b
Revises: add_hit_distance_sc
Create Date: 2025-07-30 00:28:30.643803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e423d8523b'
down_revision: Union[str, Sequence[str], None] = 'add_hit_distance_sc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_events', sa.Column('raw_description', sa.Text(), nullable=True))
    op.add_column('statcast_events', sa.Column('event_type', sa.String(length=30), nullable=True))
    op.drop_column('statcast_events', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_events', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('statcast_events', 'event_type')
    op.drop_column('statcast_events', 'raw_description')
    # ### end Alembic commands ###
