"""remove recap_video_url from games

Revision ID: 1b749299ead3
Revises: 3dcc39d5448a
Create Date: 2025-07-28 22:08:19.267739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b749299ead3'
down_revision: Union[str, Sequence[str], None] = '3dcc39d5448a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'recap_video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('recap_video_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
