"""add recap_video_url to games

Revision ID: 3dcc39d5448a
Revises: b32a7bdf0c9e
Create Date: 2025-07-28 22:04:25.272882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcc39d5448a'
down_revision: Union[str, Sequence[str], None] = 'b32a7bdf0c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('recap_video_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'recap_video_url')
    # ### end Alembic commands ###
