"""add statcast_events table

Revision ID: 89a0b83cb597
Revises: f09e3c727d0c
Create Date: 2025-07-28 00:46:15.311488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a0b83cb597'
down_revision: Union[str, Sequence[str], None] = 'f09e3c727d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statcast_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_game_pk', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.String(length=30), nullable=False),
    sa.Column('batter_name', sa.String(length=100), nullable=True),
    sa.Column('pitcher_name', sa.String(length=100), nullable=True),
    sa.Column('pitch_type', sa.String(length=10), nullable=True),
    sa.Column('launch_speed', sa.Integer(), nullable=True),
    sa.Column('launch_angle', sa.Integer(), nullable=True),
    sa.Column('estimated_ba', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statcast_events_id'), 'statcast_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statcast_events_id'), table_name='statcast_events')
    op.drop_table('statcast_events')
    # ### end Alembic commands ###
