"""add video_url to statcast_events

Revision ID: b32a7bdf0c9e
Revises: add_clip_uuid
Create Date: 2025-07-28 21:49:36.760405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32a7bdf0c9e'
down_revision: Union[str, Sequence[str], None] = 'add_clip_uuid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_events', sa.Column('video_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_events', 'video_url')
    # ### end Alembic commands ###
