"""Add context fields to statcast events

Revision ID: d2089cb95154
Revises: 5f8393b35565
Create Date: 2025-09-04 19:30:19.345484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2089cb95154'
down_revision: Union[str, Sequence[str], None] = '5f8393b35565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_events', sa.Column('inning', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('inning_topbot', sa.String(length=3), nullable=True))
    op.add_column('statcast_events', sa.Column('outs_when_up', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('away_score', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('post_home_score', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('post_away_score', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('on_1b', sa.String(length=100), nullable=True))
    op.add_column('statcast_events', sa.Column('on_2b', sa.String(length=100), nullable=True))
    op.add_column('statcast_events', sa.Column('on_3b', sa.String(length=100), nullable=True))
    op.add_column('statcast_events', sa.Column('balls', sa.Integer(), nullable=True))
    op.add_column('statcast_events', sa.Column('strikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_events', 'strikes')
    op.drop_column('statcast_events', 'balls')
    op.drop_column('statcast_events', 'on_3b')
    op.drop_column('statcast_events', 'on_2b')
    op.drop_column('statcast_events', 'on_1b')
    op.drop_column('statcast_events', 'post_away_score')
    op.drop_column('statcast_events', 'post_home_score')
    op.drop_column('statcast_events', 'away_score')
    op.drop_column('statcast_events', 'home_score')
    op.drop_column('statcast_events', 'outs_when_up')
    op.drop_column('statcast_events', 'inning_topbot')
    op.drop_column('statcast_events', 'inning')
    # ### end Alembic commands ###
