"""add venue and team id columns

Revision ID: f09e3c727d0c
Revises: b39c2af5f5c6
Create Date: 2025-07-27 23:29:18.587746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f09e3c727d0c'
down_revision: Union[str, Sequence[str], None] = 'b39c2af5f5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_team_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('venue_name', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('weather', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('games', 'venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('venue', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('games', 'weather')
    op.drop_column('games', 'venue_name')
    op.drop_column('games', 'venue_id')
    op.drop_column('games', 'away_team_id')
    op.drop_column('games', 'home_team_id')
    # ### end Alembic commands ###
