name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: game_log
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt ruff black pytest httpx

      - name: Lint (ruff)
        run: ruff .

      - name: Check formatting (black)
        run: black --check .

      - name: Run tests
        run: pytest -q

      - name: Build & run containers
        run: |
          docker compose up -d --build
          sleep 5  # give API a moment to start
          curl -f http://localhost:8000/health 